public class NB_Constants {

    public static final String DATE_FORMAT='YYYY-MM-dd';
    public static final String EMAIL_TEMPLATE_NAME='Survey';
    
    public static final String LIMIT_EXCEP_MSG='Limit for Email has exceded';
    public static final String ADMIN_EXCEP_EMAIL_SUBJ='Error while executig batch with Job Id';
    public static final String ADMIN_EXCEP_EMAIL_BODY1='The Email limit has reached for the Salesforce Org, Hence few of the following records were not processed \n';
    public static final String ADMIN_EXCEP_EMAIL_BODY2='The record with ContactId ';
    public static final String ADMIN_EXCEP_EMAIL_BODY3=' failed due to ';
    public static final String DML_EXCEP_MSG='Record failed to save due to dml Exception ';
    
      
    
}